= k6 Load Testing Demo

This repository contains a demo to show the usage of k6 as a load generator.

== Setup
- Download and install k6 (https://k6.io/docs/getting-started/installation) or use docker container.
- Start k6 with a load testing script `k6 run loadTest.js`

== Branches
=== mainline
The mainline branch shows how k6 can be used locally and without any additional dependencies.
Run script via `k6 run loadTest.js`. VUs and duration can be startup parameters: `k6 run --vus 10 --duration 30s loadTest.js`

==== Docker Usage
k6 can be used via docker. Run the container via `docker run -v ~/git/k6-performance-tests/:/src -i loadimpact/k6 run /src/loadTest.js`

==== Docker and Grafana Usage
k6 can report to influx (or other timetable series databases) and grafana to visualize the results. On first run: 
- Start the grafana and influx containers via `docker-compose up -d --build`
- Setup Grafana password at `localhost:3000`
- Setup Grafana Dashboard
- Run k6 so that it reports to influx `docker run --network k6-performance-tests_default -v ~/git/k6-performance-tests/:/src -i loadimpact/k6 run --out "influxdb=http://admin:admin@influxdb:8086/k6db" /src/loadTest.js`

=== webpack
The webpack branch shows the usage of external dependencies when k6 is running inside a docker container.
- Run `npm i` to install all dependencies
- Run `npm run bundle` to generate bundle
- Use `dist/main.bundle.js` as test source via `docker run --network k6-performance-tests_default -v ~/git/k6-performance-tests/dist:/src -i loadimpact/k6 run --out "influxdb=http://admin:admin@influxdb:8086/k6db" /src/main.bundle.js`
- Run `npm run test` to run bundling and load tests

=== groups 
The groups branch shows how tests can be structured via groups. 

=== Postman Export
k6 scripts can be generated from jmeter or postman collections via `postman-to-k6`. Also available as docker container. 
- Run `npm i -D postman-to-k6`
- Run `npm run convert`
- Run k6 with `k6-script.js`: `k6 run k6-script.js`